# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'xiaoquchaoshi' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking'
pod 'SDWebImage'
pod 'FMDB'
  # Pods for xiaoquchaoshi

  target 'xiaoquchaoshiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'xiaoquchaoshiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
